// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/shintaro-uchiyama/pkg/application"
	"github.com/shintaro-uchiyama/pkg/infrastructure"
	"github.com/shintaro-uchiyama/pkg/presentation"
)

// Injectors from wire.go:

func InitializeEvent() (*presentation.EventHandler, error) {
	secretManager, err := infrastructure.NewSecretManager()
	if err != nil {
		return nil, err
	}
	eventSlack := infrastructure.NewEventSlack()
	verifyApplication := application.NewVerifyApplication(secretManager, eventSlack)
	pubSub, err := infrastructure.NewPubSub()
	if err != nil {
		return nil, err
	}
	taskApplication := application.NewTaskApplication(pubSub)
	eventHandler := presentation.NewEventHandler(verifyApplication, taskApplication)
	return eventHandler, nil
}
